# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b78805724b33991d0cc64235694cafd418ccfd258194d6cd4408c82d7e987fd77005e002d53d91a3569d0ef5162bcbcbca116bc88bacf2f6cb68cdf714009e2a

test:
  secret_key_base: 66bdf51c66ee63701332d321bfa7f2193ca339acc2d78826c19f0574bd2e83e3fd57faa50151c15ab916964edb8e19f524cf84716eb840e717a9a762751acce3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
